language: java

sudo: required

jdk:
  - oraclejdk9

#cache:
#  directories:
#    - $HOME/.m2/repository/

script:
  -  mvn -e verify deploy

#language: java
#
#jdk:
#  - oraclejdk8
#
#cache:
#  directories:
#    - $HOME/.m2/repository/
#
#install:
#  - git clone https://github.com/cloud-native-java/build.git
#  - ./build/install.sh $CF_USER $CF_PASSWORD $CF_ORG $CF_SPACE
#
#script:
#  - ./build/script.sh $CF_USER $CF_PASSWORD $CF_ORG $CF_SPACE
